### PR TITLE
Synchronous RPC call

### LINKED ISSUE #54: Add support for synchronous RPC calls
RPC calls are asynchronous as `_execute_monkey_patch` doesn't effect them. This is annoying because all the other calls in supabase-py are synchronous.

### PR DESCRIPTION
**Pull request by bariqhibat**
Signed-off-by: Bariq <bariqhibat@gmail.com>

This PR resolves #54

### CODE REVIEW

**Comment by J0** [comment]
Hey @bariqhibat,

Any updates on this?

**Comment by bariqhibat** [comment]
Hey @J0, sorry I totally forgot about this. 
I'll push a new commit by the end of this week, got deadlines coming. Thanks for the reminder!

**Comment by J0** [comment]
Okay! No rush, no worries, looking forward to it :)

**Comment by dreinon** [comment]
Hey @bariqhibat! Postgrest-py recently added a sync client. Therefore, I recommend you point to the master branch of postgrest-py temporarily until we release a new version, and directly use this new sync client here.

**Comment by bariqhibat** [comment]
> Hey @bariqhibat! Postgrest-py recently added a sync client. Therefore, I recommend you point to the master branch of postgrest-py temporarily until we release a new version, and directly use this new sync client here.

Hey @dreinon, I see. How do I exactly do that? Should I close this PR and create a new one that points to that repo instead?

**Comment by dreinon** [comment]
Just uninstall postgrest-py and install it again using the gh repo master branch.
`poetry add git+https://github.com/supabase-community/postrest-py.git@master`

**Comment by bariqhibat** [comment]
> Just uninstall postgrest-py and install it again using the gh repo master branch. `poetry add git+https://github.com/supabase-community/postgrest-py.git@master` This will update the dependency files.

Oh, but not really sure how this would change this PR though. If the master branch in this is already updated with the latest dependencies, then I could just pull from master and resolve the conflicts. Then this PR can just change these 4 files (which is only 1 file actually)

**Comment by dreinon** [comment]
There are both changes in develop branch that have to be rebased here (like the use of httpx instead of requests) and also what I meant with the new postgrest-py update is that instead of calling postgrest-py method if async and do your own thing if it's sync, now postgrest-py has both a sync and async client, so this should be used.

**Comment by dreinon** [comment]
Hi @bariqhibat.
I'm closing this issue since we are going with the @leynier contribution which already uses the new postgrest-py sync client. But you still have done a good job and I also would like to thank you for this contribution in the name of all maintainers of this project. Thanks!

**Pull request closed without merging**
