### PR TITLE
Custom exception class, URL & Key validation using RegEx, typo fixes.

### PR DESCRIPTION
**Pull request by rawandahmad698**
## What kind of change does this PR introduce?

Creates a custom exception class for easier debugging. Fixes some typos, Adds `URL` & `Key` validation using RegEx

## What is the current behavior?

Currently, `Exception` and `BaseException` are thrown, which can make your code prone to errors and difficult to maintain

## What is the new behavior?

Adds a custom exception class.

### CODE REVIEW

**Comment by mansueli** [comment]
This merge is failing because of the test on:

https://github.com/supabase-community/supabase-py/blob/develop/tests/test_function_configuration.py

Could you rewrite the test there @rawandahmad698, so it passes the test? 
It looks really good otherwise.

**Comment by rawandahmad698** [comment]
Yessir I can

**Comment by rawandahmad698** [comment]
@mansueli Fixed

**Review by mansueli — APPROVED** [review]

**Review by J0 — APPROVED** [review]

**Comment by J0** [comment]
Hey @rawandahmad698 

Thanks for this PR! We're almost at the point we can merge -- seems like the tests are failing as the pre-commit hook (black) hasn't run.

Do you mind running the necessary formatters over the code so that the tests pass?

**Comment by rawandahmad698** [comment]
> Hey @rawandahmad698
> 
> Thanks for this PR! We're almost at the point we can merge -- seems like the tests are failing as the pre-commit hook (black) hasn't run.
> 
> Do you mind running the necessary formatters over the code so that the tests pass?

Could you please clarify? All the tests are OK on my end.

**Comment by J0** [comment]
So that CI passes* you can take a look at the CI checks for [8244244](https://github.com/supabase-community/supabase-py/pull/289/commits/8244244638bcb2bfe17c5718e28f453dce46132f)

**Comment by rawandahmad698** [comment]
> So that CI passes* you can take a look at the CI checks for [8244244](https://github.com/supabase-community/supabase-py/pull/289/commits/8244244638bcb2bfe17c5718e28f453dce46132f)
> 
> You might want to run `poetry run pre-commit run --all-files` to run the necessary formatting checks

All good, thank you
trim trailing whitespace.................................................Passed
check for added large files..............................................Passed
fix end of files.........................................................Passed
mixed line ending........................................................Passed
isort....................................................................Passed
autoflake................................................................Passed
black....................................................................Passed
pyupgrade................................................................Passed

**Comment by J0** [comment]
Hey @rawandahmad698 yup it looks perfect now,

Thanks for your patience with us and we appreciate your effort on this PR! 
Do let us know if there's anything else that we can help you with

**Comment by rawandahmad698** [comment]
Appreciate your help, will continue opening PR's :)

**Pull request merged**
