### PR TITLE
Add some default headers to wrapped client libs

### PR DESCRIPTION
**Pull request by lqmanh**
## What kind of change does this PR introduce?

Add some default headers to wrapped client libs.

## What is the current behavior?

See #42.

## Additional context

Some other minor changes included:
- Add Black as a dev dependency, because we use it in the pre-commit hook.

### CODE REVIEW

**Comment by lqmanh** [comment]
@fedden Would you mind having a quick look at this?

**Comment by J0** [comment]
LGTM but will await @fedden 's review

**Comment by J0** [comment]
@lqmanh think @fedden might be busy. If you'd be okay with it let's wait a day and merge?

Let me know what you think!
- JL

**Comment by lqmanh** [comment]
@J0 Uhm I believe that's fine. It's pretty similar to `supabase-js` version.

**Comment by J0** [comment]
merged, Thanks!

**Pull request merged**
