### PR TITLE
Add maintainers file

### PR DESCRIPTION
**Pull request by J0**
As discussed in #99 

Adding information about the contribution process in a bit

### CODE REVIEW

**Comment by J0** [comment]
Seems like I can't request for a review from @leynier and @anand2312 directly so just tagging them here.

Would anyone like to bring up anything we should address w.r.t the review process?

Lmk!

**Review by anand2312 — APPROVED** [review]
LGTM

**Review by dreinon — APPROVED** [review]

**Comment by dreinon** [comment]
Let's wait for @leynier and we can merge

**Review by leynier — APPROVED** [review]

**Comment by leynier** [comment]
LGTM 👌🏼 👍🏼

**Pull request merged**
