### PR TITLE
FastAPI tutorial for Supabase-py project

### PR DESCRIPTION
**Pull request by cloudguruab**
### 🐴 Why
This tutorial should serve as an example of using supabase api to connect to your database instance and build a service to periodically cache and serve consumer credit data on client request. This project covers redis as a caching mechanism, supabase to support our postgres instance, and fastapi for our framework. 

### ☂️ Setting up your environment

Setup your virtual environment:

```bash
python3 -m venv env 
```

Activating your environment

```zsh 
source env/bin/activate
```

In the root directory run the following:

```bash
pip install -r requirements.txt
```

### 🤖 Starting Redis in development environment

To begin working with redis, run the following command, after completion open a new terminal window.

```zsh
redis-server
```

### 👾 Activating your development server

To start your local server run the following command

```zsh
uvicorn main:app --reload
```

On success of the commad you should see;

```zsh
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [13385] using watchgod
INFO:     Started server process [13387]
2022-02-11 19:32:12,509:INFO - Started server process [13387]
INFO:     Waiting for application startup.
2022-02-11 19:32:12,509:INFO - Waiting for application startup.
2022-02-11 19:32:12,510:INFO -  02/11/2022 07:32:12 PM | CONNECT_BEGIN: Attempting to connect to Redis server...
2022-02-11 19:32:12,511:INFO -  02/11/2022 07:32:12 PM | CONNECT_SUCCESS: Redis client is connected to server.
INFO:     Application startup complete.
2022-02-11 19:32:12,511:INFO - Application startup complete.
```

### 🎾 Endpoints

Introduction to your application. 
```bash
http "http://127.0.0.1:8000/"

HTTP/1.1 200 OK
content-length: 102
content-type: application/json
date: Wed, 16 Feb 2022 22:01:14 GMT
server: uvicorn

{
    "👋 Hello": "Please refer to the readme documentation for more or visit http://localhost:8000/docs"
}
```

Working with your redis cache, the following call will pull data 
from your supabase database, and cache it. 

The x-fastapi-cache header field indicates that this response was found in the Redis cache (a.k.a. a Hit). 

The only other possible value for this field is Miss. The expires field and max-age value in the cache-control field indicate that this response will be considered fresh for 604321 seconds(1 week). This is expected since it was specified in the @cache decorator.

The etag field is an identifier that is created by converting the response data to a string and applying a hash function. If a request containing the if-none-match header is received, any etag value(s) included in the request will be used to determine if the data requested is the same as the data stored in the cache. If they are the same, a 304 NOT MODIFIED response will be sent. If they are not the same, the cached data will be sent with a 200 OK response.

```bash
# Command
http "http://127.0.0.1:8000/cachedResults"

# Response Headers
HTTP/1.1 200 OK
cache-control: max-age=604321
content-length: 894
content-type: application/json
date: Wed, 16 Feb 2022 21:53:56 GMT
etag: W/-9174636245072902018
expires: Wed, 23 Feb 2022 21:45:57 GMT
server: uvicorn
x-supafast-cache: Hit
```

### Docs

- [Installing Redis](https://redis.io/topics/quickstart)
- [Setting up Supabase](https://supabase.com/docs/reference)
- [Getting started with FastApi](https://fastapi.tiangolo.com/tutorial/)
- [Tutorial Author](https://github.com/cloudguruab)

### CODE REVIEW

**Comment by J0** [comment]
Hey!

Thanks for your PR!  We have acknowledged the PR and will look into it once a slot frees up :) Feel free to bump us if we don't get back to you within a week.

Joel

**Comment by cloudguruab** [comment]
@J0 hey been a while since I have heard back on this, any luck with this?

**Comment by J0** [comment]
@cloudguruab Sorry, just got around to looking into this. The content looks great but do you mind running the necessary linters so that CI passes? I think you need to run `black` and `isort`

**Comment by J0** [comment]
Hey @cloudguruab,

Couldn't find an email on your profile so thought I'd reach you here - we might remove the examples from the supabase-py repository the end of the week as it's a hassle to keep the dependencies up to date.

Would you like to consider moving this tutorial to [the main Supabase repository instead](https://github.com/supabase/supabase/tree/master/apps/docs/pages/guides) ? I can guide you through where to place the PR and It'd probably get more visibility there as well.

Do let me know! I'll be deleting the `examples` folder end of week but will be sure to leave a copy of it on another branch in case you want to reference it.

Jo

**Comment by J0** [comment]
Hey @cloudguruab,

Feel free to file a PR against [this directory](https://github.com/supabase/supabase/tree/master/apps/docs/pages/guides/getting-started/tutorials) and tag me in it - you can take a look at the other framework tutorials for reference if you'd like.

Let me know if there are questions

Jo

**Comment by cloudguruab** [comment]
@J0 apologies on the late response - I'll begin looking at this shortly. By chance are there any ways to integrate Django ORM or Django with Supabase? I have a need for it and would love to work on something if it doesnt exist

**Comment by cloudguruab** [comment]
Sweet, i'll ping you there and I was hoping to use django models but I assume that sticking with supabase syntax could be the easiest approach for development, i'll ping you on discord this afternoon

**Pull request merged**
