### PR TITLE
Adhere to github flavoured markdown syntax

### PR DESCRIPTION
**Pull request by tinvaan**
## What kind of change does this PR introduce?

Minor docs update - fixes several linter errors/warnings for markdown files and conforms to [Github flavoured markdown ](https://github.github.com/gfm/) syntax. 

Changes are auto-generated using `mdformat`'s [github flavoured markdown plugin](https://mdformat.readthedocs.io/en/stable/users/plugins.html) and also included as a pre-commit hook.

Closes https://github.com/supabase-community/supabase-py/issues/698

### CODE REVIEW

**Comment by J0** [comment]
Hey, 

Thanks for the PR! Do you mind resolving the conflicts? I think this change should be fine. Thanks for the contribution! 🙏

**Comment by tinvaan** [comment]
@J0 done 👍🏼 Thanks for looking into this ❤️

**Review by J0 — APPROVED** [review]
Thanks!

**Comment by J0** [comment]
Really sorry @tinvaan, could you run the pre-commit hook on the codebase again? Think the CHANGELOG.md resolution I made doesn't conform to linter requirements. Feel free to merge once the tests pass

**Comment by tinvaan** [comment]
@J0 no probs, I just rebased and force-pushed to the branch after running the `mformat` tool on the CHANGELOG & regnerating the `poetry.lock` lockfile.

I don't see the option to merge though. Can you help? I'll raise subsequent changesets for #697 & #698 against this base.

**Pull request merged**
