### PR TITLE
feat: unify http client to be httpx

### LINKED ISSUE #82: Unify HTTP Client to be httpx
As mentioned in [this conversation](https://github.com/supabase-community/gotrue-py/pull/23/files#r744137183), `requests` module should be switched to unify `httpx` module as the HTTP Client for all Supabase Python libs.
@leynier Could you do this?

### PR DESCRIPTION
**Pull request by leynier**
Resolve #82

### CODE REVIEW

**Review by dreinon — APPROVED** [review]

**Comment by dreinon** [comment]
Update tests pls @leynier

**Comment by leynier** [comment]
> Update tests pls @leynier 

The import error occurs inside the gotrue-py library, apparently the old version of gotrue-py used requests without including it in its dependencies but being included in the supabase-py dependencies the tests worked fine

**Comment by leynier** [comment]
It is necessary to publish a new version of `gotrue-py` or point to the `main` branch as it was done with `postgrest-py`

**Comment by dreinon** [comment]
Let's point the main branch for now

**Comment by leynier** [comment]
> Let's point the main branch for now

I target the latest commits specifically, to avoid unexpected internal changes.

**Comment by leynier** [comment]
I'm fixing the tests right now

**Pull request merged**
